name: mpGEMM CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     # ---------- Install toolchain ----------
      - name: Install compiler & deps
        run: sudo apt-get update && sudo apt-get install -y build-essential g++

      # ---------- Install Intel oneAPI MKL ----------
      - name: Add Intel oneAPI apt repo
        run: |
          wget -qO- https://apt.repos.intel.com/oneapi/gpgkey | sudo apt-key add -
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneapi.list
          sudo apt-get update
          sudo apt-get install -y intel-oneapi-mkl-devel

      # ---------- Export MKLROOT so Makefile can find it ----------
      - name: Set MKLROOT env
        run: echo "MKLROOT=/opt/intel/oneapi/mkl/latest" >> $GITHUB_ENV

      # ---------- Build ----------
      - name: Build project (MKL enabled)
        run: make USE_MKL=1

      # ---------- Run tests ----------
      - name: Run main test
        run: |
          make run
          # python3 scripts/benchmark.py 100

      - name: Run correctness test
        run: make test
