name: mpGEMM CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -qy install \
               build-essential g++ \
               intel-mkl-full python3 python3-pytest  python3-pybind11

      - name: Build project
        run: |
          make USE_MKL=1

      - name: Run main test
        run: |
          make run
          # python3 scripts/benchmark.py 100

      - name: Run correctness test
        run: make test
